controller_manager:
  ros__parameters:
    update_rate: 225  # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    position_controller:
      type: position_controllers/JointGroupPositionController

joint_state_broadcaster:
  ros__parameters:
    type: joint_state_broadcaster/JointStateBroadcaster
    publish_rate: 50

joint_position_controller:
  ros__parameters:
    joints:
      - j0
      - j1
      - j2
      - j3
    state_publish_rate: 50
    command_interfaces:
      - position